---
engines:
 duplication:
   exclude_paths:
     - data/instrujs/common.js
     - data/instrujs/common.min.js
     - data/instrujs/confstat.js
     - instrujs/enginedjg/src/statemachine.js
     - instrujs/timestui/src/statemachine.js
exclude_paths:
  - 'data/instrujs/*.min.js'
  - 'data/instrujs/**/bundle.js'
  - 'data/instrujs/**/bundle.css'
  - 'docs/**/*.md'
